import type { NextPage } from 'next'
import Head from 'next/head'
import { Bot } from '../components/BotButton'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samehadakuu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bot />
    </div>
  )
}

export default Home
