import type { NextPage } from 'next'
import Head from 'next/head'
import { Bot } from '../components/BotButton'
import styles from '../styles/Home.module.scss'
import Main from '../components/Main'

import Navbar from '../components/Navbar'
const Home: NextPage = () => {
  return (
    <Main>
      <div>
        <Head>
          <title>Samehadakuu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.container}>
          <Bot />
        </div>
      </div>
    </Main>
  )
}

export default Home
